# Generated by Django 5.0.6 on 2024-07-13 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FilterCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_category_code", models.CharField(max_length=255)),
                ("filter_category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holiday_date", models.DateField()),
                ("holiday_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OrderingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_code", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ViewOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_code", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FilterOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_option_code", models.CharField(max_length=255)),
                ("filter_option", models.CharField(max_length=255)),
                (
                    "filter_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.filtercategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=5)),
                (
                    "currency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.currency"
                    ),
                ),
                (
                    "exchange_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.exchange"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("quantity", models.IntegerField()),
                (
                    "side",
                    models.CharField(
                        choices=[("B", "Buy"), ("S", "Sell")], max_length=1
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.instrument"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "pl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "pl_type",
                    models.CharField(
                        choices=[
                            ("day_1", "Day 1"),
                            ("mtm", "Mark To Market"),
                            ("brokerage", "Brokerage"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.instrument"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClosePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.instrument"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("filter", models.JSONField()),
                (
                    "ordering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.orderingoption",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.viewoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilterResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("COB_date", models.DateField()),
                ("run_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("results", models.JSONField()),
                (
                    "filter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.savedfilter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("quantity", models.IntegerField()),
                (
                    "side",
                    models.CharField(
                        choices=[("B", "Buy"), ("S", "Sell")], max_length=1
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "brokerage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("account", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "brokerage_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.currency",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.instrument"
                    ),
                ),
            ],
        ),
    ]
